"""Reading a harness's own report, and what it declines to infer.

THE PAYLOADS HERE ARE NOT WRITTEN HERE. They come from
`governance/qm/project-seed/harness-payload-vectors.json`, which the harness
generated by running its own emitter against a database built from its own
models. Neither project imports the other; what is shared is the cases, exactly
as it is for the address grammar.

This replaced a dict written in this file. That dict was schema 1, claimed
totals no harness had produced, and carried a status -- `FAILURE` -- that the
harness's enum has never contained. It agreed with a hand-written fixture on
the other side of the seam and with nothing else, and both suites were green.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from sqlmodel import Session, SQLModel, create_engine, select

from dossier import harness
from dossier.models.harness import HarnessInvocation, HarnessSnapshot

ROOT = Path(__file__).resolve().parent.parent.parent
VECTORS = ROOT / "governance" / "qm" / "project-seed" / "harness-payload-vectors.json"


def contract() -> dict:
    if not VECTORS.is_file():
        pytest.fail(
            f"{VECTORS.relative_to(ROOT).as_posix()} is absent. The payload "
            f"contract ships through the governance submodule; without it this "
            f"reader is verified against a fixture of its own invention, which "
            f"is what made the seam wrong."
        )
    document = json.loads(VECTORS.read_text(encoding="utf-8"))
    assert document["cases"], "an empty vector file verifies nothing"
    return document


def case(fragment: str, whole: bool = False) -> dict:
    """The one contract case whose name contains `fragment`.

    Its payload by default; the whole entry, with its `accepted` flag, when
    `whole` is set.
    """
    matches = [c for c in contract()["cases"] if fragment in c["name"]]
    assert len(matches) == 1, f"{fragment!r} matched {len(matches)} cases"
    return matches[0] if whole else matches[0]["payload"]


def payload(**overrides) -> dict:
    """A real payload from a harness that has run things."""
    document = dict(case("has run things"))
    document.update(overrides)
    return document


def first_address(document: dict | None = None) -> str:
    return (document or payload())["recent"][0]["address"]


def first_status(document: dict | None = None) -> str:
    return (document or payload())["recent"][0]["status"]


@pytest.fixture()
def session():
    engine = create_engine("sqlite://")
    SQLModel.metadata.create_all(engine)
    with Session(engine) as s:
        yield s


def lookup_for(session):
    def lookup(address):
        return session.exec(
            select(HarnessInvocation).where(HarnessInvocation.address == address)
        ).first()
    return lookup


# --- reading -----------------------------------------------------------------


def test_a_payload_of_the_wrong_schema_is_refused(session):
    verdicts = harness.plan(payload(schema=99), lookup_for(session))
    assert [v.state for v in verdicts] == ["refused"]
    assert "schema 99" in verdicts[0].reason


def test_a_payload_missing_its_totals_is_refused(session):
    document = payload()
    del document["totals"]
    verdicts = harness.plan(document, lookup_for(session))
    assert verdicts[0].state == "refused"
    assert "totals" in verdicts[0].reason


def test_a_row_without_an_address_is_not_stored(session):
    """An invented identity is one that will not match the same row next time."""
    document = payload(recent=[{"tool_name": "echo"}, 
                               {"address": "a/b/invocation/x", "tool_name": "echo"}])
    assert [row["address"] for row in harness.invocations_of(document)] == \
        ["a/b/invocation/x"]


def test_totals_are_read_verbatim(session):
    """Verbatim means the payload's own numbers, whatever they are.

    This asserted four literals copied from a fixture written in this file. It
    would have kept passing against a harness that had changed what it counts.
    """
    document = payload()
    assert harness.totals_of(document) == {
        name: document["totals"][name]
        for name in ("invocations", "failures", "human_requests", "human_responses")}


def test_the_excerpt_does_not_become_the_totals(session):
    """Recomputing from the rows would report the size of the excerpt.

    Read from the one contract case where the two genuinely differ. Every other
    case has as many rows as invocations, and a test written against one of
    those cannot fail however the totals are derived -- which is what the
    fixture this replaced was doing.
    """
    document = case("recent list is an excerpt")
    rows = len(harness.invocations_of(document))
    counted = harness.totals_of(document)["invocations"]
    assert rows < counted, "this case exists so the two differ"
    assert counted == document["totals"]["invocations"]


# --- ingesting ---------------------------------------------------------------


def test_a_first_read_is_all_new(session):
    document = payload()
    verdicts = harness.plan(document, lookup_for(session))
    assert [v.state for v in verdicts] == ["new"] * (1 + len(document["recent"]))


def test_a_changed_status_is_a_disagreement_not_a_correction(session):
    """The stored status is one the harness really can produce.

    It used to be `FAILURE`, which the harness's enum does not contain, so the
    disagreement this test asserted was between a real value and a fictional
    one.
    """
    document = payload()
    stored = next(status for status in contract()["status_vocabulary"]["values"]
                  if status != first_status(document))
    session.add(HarnessInvocation(address=first_address(document),
                                  project=document["project"],
                                  tool_name=document["recent"][0]["tool_name"],
                                  status=stored))
    session.commit()
    verdicts = harness.plan(document, lookup_for(session))
    differing = [v for v in verdicts if v.state == "differs"]
    assert differing
    assert "status" in differing[0].differences[0]


def test_an_unchanged_row_reads_as_matching(session):
    document = payload()
    row = document["recent"][0]
    session.add(HarnessInvocation(address=row["address"], project=document["project"],
                                  tool_name=row["tool_name"], status=row["status"],
                                  error=row["error"]))
    session.commit()
    states = [v.state for v in harness.plan(document, lookup_for(session))]
    assert "same" in states


# --- the contract, which the harness is held to as well ----------------------


@pytest.mark.parametrize("entry", contract()["cases"], ids=lambda c: c["name"])
def test_every_contract_case_is_handled_as_the_contract_says(entry, session):
    """Real emitter output, through this reader, with no fixture in between.

    `accepted` is the contract's word for whether this side must ingest the
    payload. False means refused with a reason -- which is a different outcome
    from ingesting it and recording zeros, and telling those two apart is the
    whole reason this file stopped writing its own payloads.
    """
    verdicts = harness.plan(entry["payload"], lookup_for(session))
    refused = [v for v in verdicts if v.state == "refused"]
    if entry["accepted"]:
        assert not refused, f"{entry['name']}: {[v.reason for v in refused]}"
    else:
        assert refused, f"{entry['name']}: accepted a payload the contract refuses"
        assert refused[0].reason, "a refusal must say why"


def test_a_harness_that_could_not_count_is_not_stored_as_one_that_counted_zero(session):
    """The defect this schema version exists for.

    An unreadable harness and an idle one both reported zero invocations, and
    this reader coerced both into the database as fact. They are told apart by
    whether the count was taken, and NOT by the table count: the two refused
    cases in the contract carry different table counts and neither is readable.
    """
    idle = case("has run nothing")
    broken = case("unrelated tables")

    assert idle["totals"]["invocations"] == 0
    assert harness.unknown_totals(idle) == []
    assert [v.state for v in harness.plan(idle, lookup_for(session))][0] == "new"

    assert harness.unknown_totals(broken), "the harness said it could not count"
    verdict = harness.plan(broken, lookup_for(session))[0]
    assert verdict.state == "refused"
    assert verdict.differences, "the refusal names which counts were unknown"

    assert idle["totals"]["tables"] != broken["totals"]["tables"], (
        "the two differ in table count, which is why the table count cannot be "
        "what tells a readable harness from an unreadable one"
    )


def test_totals_are_never_coerced(session):
    """A total the payload does not carry is absent, never zero.

    THE FIRST VERSION OF THIS TEST WAS INERT. It asserted that `totals_of`
    raises on an unknown, and the coerced form raises too -- `int()` of a
    non-empty dict is a TypeError either way -- so it passed against the
    defect it was written for. What actually distinguishes them is a MISSING
    key: `int(totals.get(name, 0) or 0)` invents a zero for it, and this form
    leaves it out.
    """
    document = payload()
    assert harness.totals_of(document)["invocations"] ==         document["totals"]["invocations"]

    thin = dict(document, totals={"invocations": 7})
    totals = harness.totals_of(thin)
    assert totals == {"invocations": 7}, (
        "a total nobody sent must not arrive as zero"
    )
    for name in ("failures", "human_requests", "human_responses"):
        assert name not in totals


def test_the_report_says_nothing_was_written(session):
    text = harness.render(harness.plan(payload(), lookup_for(session)), written=False)
    assert "Nothing was written" in text
    assert "--write" in text


def test_the_report_states_that_nothing_is_deleted(session):
    """The payload is an excerpt by construction, so absence means nothing."""
    text = harness.render(harness.plan(payload(), lookup_for(session)), written=True)
    assert "not one that was removed" in text


def test_loading_a_list_is_refused(tmp_path: Path):
    path = tmp_path / "wrong.json"
    path.write_text(json.dumps([{"schema": 1}]), encoding="utf-8")
    with pytest.raises(ValueError):
        harness.load(path)


# --- the exit status, which a scheduler is the only reader of ----------------


def _ingest(tmp_path, entry) -> int:
    """Run the real CLI against one contract case; return its exit status."""
    from click.testing import CliRunner

    from dossier.cli import cli

    payload_file = tmp_path / "payload.json"
    payload_file.write_text(json.dumps(entry["payload"]), encoding="utf-8")
    return CliRunner().invoke(
        cli, ["harness", "ingest", str(payload_file)]).exit_code


def test_a_refused_payload_exits_non_zero(tmp_path):
    """It exited 0, printed the refusal, and reported success to its caller.

    Nothing was written, which was right. But a scheduled ingest of an
    unreadable harness is exactly the case nobody is watching, and an exit
    status of 0 is what that caller records.
    """
    assert _ingest(tmp_path, case("unrelated tables", whole=True)) == 1


def test_a_readable_payload_exits_zero(tmp_path):
    """The other half of the pair. A refusal that fired on everything would be
    as useless as one that fired on nothing."""
    assert _ingest(tmp_path, case("has run things", whole=True)) == 0
