"""add the harness ask queue

The human-in-the-loop queue, as the control panel's copy of it. The snapshot
already said how many questions were outstanding; this says which, with the
prompt and the options, because a count is not something anybody can answer.

WHAT WAS REMOVED FROM THE AUTOGENERATED VERSION, AND WHY. Autogenerate also
emitted six `drop_index` calls against `project`, `project_component` and
`project_version`. Those indexes are real and deliberate -- they were added by
`003_add_performance_indexes` -- and they are absent from the model classes,
which is the only reason autogenerate wanted them gone. Running that migration
would have silently dropped somebody's performance work as a side effect of
adding an unrelated table. They are not in this file.

Revision ID: 4e21fe9daec9
Revises: cb1ba35f82fb
Create Date: 2026-08-20 07:20:02.179498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e21fe9daec9'
down_revision: Union[str, None] = 'cb1ba35f82fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'harness_ask',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('project', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('request_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('options', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('asked_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('answered_with', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('answered_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('answered_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('loaded_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # The address is unique: a question seen twice is the same question, and
    # ingesting it again updates the row rather than adding a second one.
    op.create_index(op.f('ix_harness_ask_address'), 'harness_ask',
                    ['address'], unique=True)
    op.create_index(op.f('ix_harness_ask_project'), 'harness_ask',
                    ['project'], unique=False)
    op.create_index(op.f('ix_harness_ask_request_id'), 'harness_ask',
                    ['request_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_harness_ask_request_id'), table_name='harness_ask')
    op.drop_index(op.f('ix_harness_ask_project'), table_name='harness_ask')
    op.drop_index(op.f('ix_harness_ask_address'), table_name='harness_ask')
    op.drop_table('harness_ask')
