"""add delta relations

How deltas compose: five relations, both sides named by address so a relation
crosses repositories and threads. `governance/qm/records/DRAFT-deltas-compose.md`
is the decision.

WRITTEN BY HAND, NOT AUTOGENERATED. Autogenerate compares the models against a
live database, and the only database on this machine at the previous head is the
operator's own. Running it there would have meant migrating real data to write a
migration -- and the previous revision in this chain had to strip six
`drop_index` calls autogenerate emitted against indexes nobody asked it to
touch. The table is small enough that writing it is cheaper than supervising it.

NO FOREIGN KEYS, AND NO ACYCLICITY CHECK. Both are deliberate. A foreign key
would make the ordinary case impossible: a relation may name a delta this
database has never ingested, because an address denotes without existing. And a
cycle is a fact about the work rather than an error in the record -- refusing to
store one does not untangle anything, it deletes the evidence that the work is
tangled. Clauses 1 and 7 of the record.

Revision ID: b7c4d1a90e33
Revises: 4e21fe9daec9
Create Date: 2026-08-20 08:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b7c4d1a90e33'
down_revision: Union[str, None] = '4e21fe9daec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'delta_relation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('relation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('target_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('stated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('proposed', sa.Boolean(), nullable=False,
                  server_default=sa.text('0')),
        sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_delta_relation_source_address'), 'delta_relation',
                    ['source_address'], unique=False)
    op.create_index(op.f('ix_delta_relation_relation'), 'delta_relation',
                    ['relation'], unique=False)
    op.create_index(op.f('ix_delta_relation_target_address'), 'delta_relation',
                    ['target_address'], unique=False)
    # One statement is one row. Saying the same thing twice is the same
    # statement, not a stronger one -- and a harness re-emitting its state on
    # every run would otherwise grow this table without bound.
    op.create_index('ix_delta_relation_statement', 'delta_relation',
                    ['source_address', 'relation', 'target_address'], unique=True)


def downgrade() -> None:
    op.drop_index('ix_delta_relation_statement', table_name='delta_relation')
    op.drop_index(op.f('ix_delta_relation_target_address'), table_name='delta_relation')
    op.drop_index(op.f('ix_delta_relation_relation'), table_name='delta_relation')
    op.drop_index(op.f('ix_delta_relation_source_address'), table_name='delta_relation')
    op.drop_table('delta_relation')
